spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/konsign
      username: konsign
      password: konsign
  jpa:
    hibernate:
      ddl-auto: create


redis:
  host: localhost
  port: 6379
  username: redis
  password: konsign