[versions]
springboot = "3.0.6"
jjwt = "0.9.1"
jaxb = "2.4.0-b180830.0359"
postgres = "42.7.8"
gson = "2.10"
lombok = "1.18.30" # put actual version you use
mapstruct = "1.5.3.Final"
springdoc = "1.6.14"
jedis = "3.9.0"
jackson = "2.15.0"
micrometer = "1.11.0" # adjust if needed
testcontainers = "1.17.6"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springboot" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis", version.ref = "springboot" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache", version = "2.4.3" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

jjwt = { module = "io.jsonwebtoken:jjwt", version.ref = "jjwt" }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb" }
postgres-connector = { module = "org.postgresql:postgresql", version.ref = "postgres" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

springdoc-openapi-ui = { module = "org.springdoc:springdoc-openapi-ui", version.ref = "springdoc" }
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }

testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testcontainers" }
